import{S as m,a as g,i as b}from"./assets/vendor-aa7a424a.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerpolicy&&(o.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?o.credentials="include":t.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const L=document.getElementById("search-form"),a=document.querySelector(".load-more"),u=document.getElementById("gallery");let n=1,c="",y=0;const f=new m(".gallery a"),v="https://pixabay.com/api/",w="41042730-e71566aaa26e0b69c1c299757",p=async(s,e,r=40)=>{try{return(await g.get(v,{params:{key:w,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:r}})).data}catch(l){return console.error("Error fetching images:",l),[]}},h=s=>{const e=s.map(r=>`
    <div class="photo-card">
      <a href="${r.largeImageURL}" data-lightbox="image">
        <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${r.likes}</p>
        <p class="info-item"><b>Views:</b> ${r.views}</p>
        <p class="info-item"><b>Comments:</b> ${r.comments}</p>
        <p class="info-item"><b>Downloads:</b> ${r.downloads}</p>
      </div>
    </div>
  `).join("");u.insertAdjacentHTML("beforeend",e)},i=s=>{b.info({message:s,theme:"dark",position:"topCenter"})};a.style.display="none";const H=()=>{y>0&&(n-1)*40<y?a.style.display="block":a.style.display="none"};L.addEventListener("submit",async s=>{if(s.preventDefault(),c=s.target.elements.searchQuery.value.trim(),c===""){i("Please enter a search term");return}n=1;const e=await p(c,n);if(e.totalHits===0){i("Sorry, there are no images matching your search query. Please try again."),u.innerHTML="",a.style.display="none";return}u.innerHTML="",y=e.totalHits,h(e.hits),f.refresh(),i(`Hooray! We found ${e.totalHits} images.`),H();const r=Math.ceil(e.totalHits/e.perPage);if(n===r){i("We're sorry, but you've reached the end of search results."),a.style.display="none";return}});a.addEventListener("click",async()=>{n++;const s=await p(c,n);if(s.hits.length===0){i("We're sorry, but you've reached the end of search results."),a.style.display="none";return}h(s.hits),f.refresh();const e=Math.ceil(s.totalHits/s.perPage);if(n===e){i("We're sorry, but you've reached the end of search results."),a.style.display="none";return}});
//# sourceMappingURL=commonHelpers.js.map
