import{S as g,a as b,i as L}from"./assets/vendor-aa7a424a.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerpolicy&&(o.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?o.credentials="include":r.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const v=document.getElementById("search-form"),l=document.querySelector(".load-more"),f=document.getElementById("gallery");let c=1,d="",p=0;const m=new g(".gallery a"),w="https://pixabay.com/api/",H="41042730-e71566aaa26e0b69c1c299757",y=async(t,e,s=40)=>{try{return(await b.get(w,{params:{key:H,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:s}})).data}catch(n){return console.error("Error fetching images:",n),[]}},h=t=>{const e=t.map(s=>`
    <div class="photo-card">
      <a href="${s.largeImageURL}" data-lightbox="image">
        <img src="${s.webformatURL}" alt="${s.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${s.likes}</p>
        <p class="info-item"><b>Views:</b> ${s.views}</p>
        <p class="info-item"><b>Comments:</b> ${s.comments}</p>
        <p class="info-item"><b>Downloads:</b> ${s.downloads}</p>
      </div>
    </div>
  `).join("");f.insertAdjacentHTML("beforeend",e)},a=t=>{L.info({message:t,theme:"dark",position:"topCenter"})};l.style.display="none";const i=()=>{p>0&&(c-1)*40<p?l.style.display="block":l.style.display="none"};l.style.display="none";v.addEventListener("submit",async t=>{if(t.preventDefault(),d=t.target.elements.searchQuery.value.trim(),d===""){a("Please enter a search term");return}c=1;const e=await y(d,c);if(e.totalHits===0){a("Sorry, there are no images matching your search query. Please try again."),f.innerHTML="",i();return}f.innerHTML="",p=e.totalHits,h(e.hits),m.refresh(),a(`Hooray! We found ${e.totalHits} images.`),i();const s=Math.ceil(e.totalHits/e.perPage);if(e.pageNumber>=s){a("We're sorry, but you've reached the end of search results."),i();return}});l.addEventListener("click",async()=>{c++;const t=await y(d,c);if(t.hits.length===0){a("We're sorry, but you've reached the end of search results."),i();return}h(t.hits),m.refresh();const e=Math.ceil(t.totalHits/t.perPage);if(t.pageNumber>=e){a("We're sorry, but you've reached the end of search results."),i();return}});
//# sourceMappingURL=commonHelpers.js.map
